Repo maintenance
qbicsoftware/experimental-design-lib pull request #17
Opened 2022-02-08 17:05 UTC by wow-such-code

2022-02-14 07:30 UTC, KochTobi requested changes

2022-02-14 07:30 UTC, KochTobi commented on README.md
> +# <p align=center>Experimental Design Library</p>
You only need one centered `div`.
https://github.com/qbicsoftware/sample-tracking-service/blob/master/README.md

2022-02-14 07:30 UTC, KochTobi commented on README.md
> +```
Very nice readme. I am missing a description on the data model as well as what exactly this library aims to provide.
Maybe an example how to use this library to parse experimental properties to openbis

2022-02-14 10:21 UTC, wow-such-code commented on .github/workflows/create-release.yml
> +              base: 'main'
good catch!

2022-02-14 10:37 UTC, wow-such-code commented on src/test/java/life/qbic/expdesign/io/MetaboDesignReaderTest.java
> +//      new File(getClass().getResource("mtx/msOptional.tsv").getFile());
good point, I rolled the change back by adding the missing test file

2022-02-24 13:49 UTC, KochTobi approved these changes

2022-02-24 14:16 UTC, merged